# Importing Library

In [1]:
import numpy as np


# Data Reading

In [2]:
data_file = '/content/drive/MyDrive/techis-ds-wiki-main/DS/Step 1-4 Data Processing/01_Numpy/makeSenseOfCensus.csv'

# Data Loading

In [3]:
data = np.genfromtxt(data_file,delimiter=',',skip_header=1)

In [4]:
print( data)

[[39. 13.  4. ...  0. 40.  0.]
 [50. 13.  4. ...  0. 13.  0.]
 [38.  9.  4. ...  0. 40.  0.]
 ...
 [48. 13.  4. ...  0. 58.  1.]
 [40. 10.  4. ...  0. 40.  0.]
 [39. 13.  4. ...  0. 50.  1.]]


In [5]:
new_record = [[50,9,4,1,0,0,40,0]]

## Step 2: Appending Data

In [6]:
data = np.concatenate((data,new_record))

In [7]:
print(data)

[[39. 13.  4. ...  0. 40.  0.]
 [50. 13.  4. ...  0. 13.  0.]
 [38.  9.  4. ...  0. 40.  0.]
 ...
 [40. 10.  4. ...  0. 40.  0.]
 [39. 13.  4. ...  0. 50.  1.]
 [50.  9.  4. ...  0. 40.  0.]]


In [8]:
age = data[:,0]


In [9]:
max_age = age.max()
print (max_age)

90.0


In [10]:
min_age = age.min()
import numpy as np
print (min_age)

17.0


In [11]:
age_mean = age.min()
print (age_mean)

17.0


In [12]:
age_std = age.std()
print (age_std)

13.341478176165857


In [13]:
race=data[:,2]
race

array([4., 4., 4., ..., 4., 4., 4.])

In [14]:
race_0= np.array(race[race==0])
race_0

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [15]:
len(race_0)

10

In [16]:
race_1 = np.array(race[race==1])
print(race_1)
race_2 = np.array(race[race==2])
print(race_2)
race_3 = np.array(race[race==3])
print(race_3)
race_4 = np.array(race[race==4])
print(race_4)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1.]
[2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2.
 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2.
 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2.
 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2.
 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2.]
[3. 3. 3. 3. 3. 3.]
[4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4.
 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4.
 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4.
 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4.
 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4.
 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4.
 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4.
 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 

In [17]:
len(race_0)

10

In [18]:
len(race_1)

27

In [19]:
len(race_2)

110

In [20]:
len(race_3)

6

In [21]:
len(race_4)

848

### Race 3 which 'other' is minority community in this country 

In [22]:
sc = age>60
senior_citizen=(data[:][sc])
senior_citizen

array([[7.9000e+01, 1.0000e+01, 4.0000e+00, 1.0000e+00, 0.0000e+00,
        0.0000e+00, 2.0000e+01, 0.0000e+00],
       [6.7000e+01, 6.0000e+00, 4.0000e+00, 1.0000e+00, 0.0000e+00,
        0.0000e+00, 2.0000e+00, 0.0000e+00],
       [7.6000e+01, 1.4000e+01, 4.0000e+00, 1.0000e+00, 0.0000e+00,
        0.0000e+00, 4.0000e+01, 1.0000e+00],
       [6.1000e+01, 9.0000e+00, 4.0000e+00, 1.0000e+00, 0.0000e+00,
        0.0000e+00, 4.0000e+01, 0.0000e+00],
       [7.0000e+01, 1.0000e+01, 4.0000e+00, 1.0000e+00, 0.0000e+00,
        0.0000e+00, 4.0000e+01, 0.0000e+00],
       [6.4000e+01, 7.0000e+00, 4.0000e+00, 1.0000e+00, 0.0000e+00,
        2.1790e+03, 4.0000e+01, 0.0000e+00],
       [7.1000e+01, 1.0000e+01, 2.0000e+00, 1.0000e+00, 0.0000e+00,
        1.8160e+03, 2.0000e+00, 0.0000e+00],
       [6.8000e+01, 2.0000e+00, 4.0000e+00, 0.0000e+00, 0.0000e+00,
        0.0000e+00, 2.0000e+01, 0.0000e+00],
       [6.6000e+01, 1.1000e+01, 4.0000e+00, 0.0000e+00, 0.0000e+00,
        0.0000e+00, 2.0000e+

In [23]:
working_hr=senior_citizen[:6]
working_hr

array([[7.900e+01, 1.000e+01, 4.000e+00, 1.000e+00, 0.000e+00, 0.000e+00,
        2.000e+01, 0.000e+00],
       [6.700e+01, 6.000e+00, 4.000e+00, 1.000e+00, 0.000e+00, 0.000e+00,
        2.000e+00, 0.000e+00],
       [7.600e+01, 1.400e+01, 4.000e+00, 1.000e+00, 0.000e+00, 0.000e+00,
        4.000e+01, 1.000e+00],
       [6.100e+01, 9.000e+00, 4.000e+00, 1.000e+00, 0.000e+00, 0.000e+00,
        4.000e+01, 0.000e+00],
       [7.000e+01, 1.000e+01, 4.000e+00, 1.000e+00, 0.000e+00, 0.000e+00,
        4.000e+01, 0.000e+00],
       [6.400e+01, 7.000e+00, 4.000e+00, 1.000e+00, 0.000e+00, 2.179e+03,
        4.000e+01, 0.000e+00]])

In [24]:
working_hr_sum=np.sum(working_hr)
working_hr_sum


2865.0

In [25]:
len(senior_citizen[:,0])

61

In [26]:
avg_working_hr=working_hr_sum/len(senior_citizen[:,0])
avg_working_hr

46.967213114754095

In [30]:
edu = data[:,1]
edu


array([13., 13.,  9., ..., 10., 13.,  9.])

In [31]:
high = edu[edu > 10]
low = edu[edu <= 10]
print(high)

[13. 13. 13. 14. 14. 13. 13. 13. 12. 11. 14. 16. 13. 12. 13. 12. 13. 13.
 13. 14. 11. 11. 15. 13. 11. 13. 16. 13. 13. 12. 13. 14. 16. 11. 13. 16.
 12. 14. 13. 14. 13. 15. 11. 13. 13. 13. 13. 12. 12. 13. 12. 14. 11. 11.
 13. 13. 13. 14. 14. 12. 14. 11. 13. 13. 13. 13. 13. 14. 16. 13. 13. 14.
 14. 14. 13. 13. 13. 12. 13. 13. 11. 15. 13. 14. 13. 12. 12. 15. 13. 11.
 13. 13. 14. 14. 13. 12. 13. 14. 15. 13. 13. 13. 13. 13. 14. 13. 12. 12.
 12. 13. 14. 13. 14. 11. 13. 11. 14. 12. 11. 13. 11. 12. 13. 13. 13. 13.
 11. 14. 13. 13. 12. 13. 11. 14. 13. 12. 13. 13. 13. 13. 11. 14. 16. 13.
 14. 14. 13. 12. 14. 13. 12. 11. 12. 13. 13. 14. 13. 11. 13. 12. 13. 13.
 13. 12. 13. 13. 13. 11. 11. 11. 13. 13. 13. 14. 12. 15. 11. 13. 16. 11.
 13. 13. 13. 14. 14. 11. 16. 13. 12. 13. 13. 13. 13. 13. 15. 13. 13. 12.
 14. 14. 13. 13. 13. 15. 13. 11. 13. 13. 13. 13. 16. 16. 13. 16. 14. 14.
 12. 13. 11. 13. 14. 13. 12. 14. 14. 13. 13. 13. 16. 13. 13. 13. 11. 13.
 13. 13. 13. 13. 11. 11. 13. 13. 14. 11. 13. 13. 13

In [32]:
print(low)

[ 9.  7.  5.  9. 10.  4.  9.  9.  7.  9.  5.  7.  9.  9. 10.  9.  9. 10.
 10. 10.  7. 10.  9. 10.  5.  9.  9.  9. 10.  9.  9. 10.  3.  9.  9.  4.
  9. 10.  9. 10.  9. 10. 10. 10. 10. 10.  9.  6.  7.  4.  9.  9.  9.  9.
  9.  9.  5. 10. 10.  9. 10. 10.  9. 10.  9.  9.  6.  7.  9.  9.  9. 10.
  9.  5. 10. 10.  9. 10. 10. 10.  9. 10.  9.  9.  9. 10. 10.  9. 10. 10.
 10.  9. 10.  9.  7. 10. 10.  9.  9.  9.  9. 10.  9.  2.  9.  9. 10.  7.
  9.  9. 10.  9.  9.  9.  9. 10. 10. 10.  4. 10.  9. 10. 10. 10.  3. 10.
  9.  9. 10.  9.  7.  9.  9.  7.  9.  9. 10.  9.  4.  6. 10.  2.  9.  9.
  1.  9.  6.  9.  9.  7.  9. 10. 10.  9. 10.  9.  9. 10. 10.  9.  9.  9.
  9.  6. 10. 10.  9.  9.  9.  4.  9.  7. 10.  7. 10. 10.  9.  9.  9.  5.
  9.  9. 10. 10. 10. 10. 10.  9. 10.  4.  9. 10.  9.  9.  9. 10.  9.  9.
 10.  9. 10. 10. 10. 10. 10.  3. 10.  9.  9. 10.  9.  7.  9. 10.  9.  9.
 10.  6.  9.  3.  9.  9.  9.  9.  9. 10.  7.  9.  7.  9.  7.  9.  5.  6.
  9.  9. 10.  9. 10.  7.  9.  9. 10.  9. 10.  9.  9

In [34]:
income = data[:,7]
avg_pay_high = np.mean(income[edu > 10])
print(avg_pay_high)

0.42813455657492355


In [35]:
avg_pay_low = np.mean(income[edu<=10])
print(avg_pay_low)

0.13649851632047477
